#pragma once

class BrewingStandBlockActor : BlockActor, Container {

    virtual void BrewingStand~BrewingStandBlockActor();
    virtual void BrewingStand~BrewingStandBlockActor();
    virtual void BrewingStandload(Level &, CompoundTag const&, DataLoadHelper &);
    virtual void BrewingStandsave(CompoundTag &)const;
    virtual void saveItemInstanceData(CompoundTag &);
    virtual void saveBlockData(CompoundTag &, BlockSource &)const;
    virtual void loadBlockData(CompoundTag const&, BlockSource &, DataLoadHelper &);
    virtual void onCustomTagLoadDone(BlockSource &);
    virtual void BrewingStandtick(BlockSource &);
    virtual void BrewingStandisFinished(void);
    virtual void BrewingStandonChanged(BlockSource &);
    virtual void isMovable(BlockSource &);
    virtual void isCustomNameSaved(void);
    virtual void getUpdatePacket(BlockSource &);
    virtual void onPlace(BlockSource &);
    virtual void onUpdatePacket(CompoundTag const&, BlockSource &);
    virtual void BrewingStandonMove(void);
    virtual void onRemoved(BlockSource &);
    virtual void triggerEvent(int, int);
    virtual void clearCache(void);
    virtual void onNeighborChanged(BlockSource &, BlockPos const&);
    virtual void getShadowRadius(BlockSource &)const;
    virtual void hasAlphaLayer(void)const;
    virtual void getCrackEntity(BlockSource &, BlockPos const&);
    virtual void getDebugText(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> &, BlockPos const&);
    virtual void _ZNK10BlockActor13getCustomNameB5cxx11Ev;
    virtual void _ZN10BlockActor21getFilteredCustomNameB5cxx11ERK18UIProfanityContext;
    virtual void _ZNK22BrewingStandBlockActor7getNameB5cxx11Ev;
    virtual void _ZN10BlockActor22getImmersiveReaderTextB5cxx11ER11BlockSource;
    virtual void getRepairCost(void)const;
    virtual void getOwningPiston(BlockSource &);
    virtual void BrewingStandgetContainer(void);
    virtual void getDeletionDelayTimeSeconds(void)const;
    virtual void onChunkLoaded(LevelChunk &);
    virtual void onChunkUnloaded(LevelChunk &);
    virtual void BrewingStandgetItem(int)const;
    virtual void BrewingStandsetItem(int, ItemStack const&);
    virtual void BrewingStandgetMaxStackSize(void)const;
    virtual void BrewingStandgetContainerSize(void)const;
    virtual void BrewingStandstartOpen(Player &);
    virtual void BrewingStandstopOpen(Player &);
    virtual void BrewingStandcanPushInItem(BlockSource &, int, int, ItemInstance const&)const;
    virtual void BrewingStandcanPullOutItem(BlockSource &, int, int, ItemInstance const&)const;
    virtual void ;
    virtual void `non-virtual thunk to'BrewingStand~BrewingStandBlockActor();
    virtual void `non-virtual thunk to'BrewingStand~BrewingStandBlockActor();
    virtual void init(void);
    virtual void addContentChangeListener(ContainerContentChangeListener *);
    virtual void removeContentChangeListener(ContainerContentChangeListener *);
    virtual void `non-virtual thunk to'BrewingStandgetItem(int)const;
    virtual void hasRoomForItem(ItemStack const&);
    virtual void addItem(ItemStack &);
    virtual void addItemToFirstEmptySlot(ItemStack &);
    virtual void `non-virtual thunk to'BrewingStandsetItem(int, ItemStack const&);
    virtual void removeItem(int, int);
    virtual void removeAllItems(void);
    virtual void dropContents(BlockSource &, Vec3 const&, bool);
    virtual void `non-virtual thunk to'BrewingStandgetContainerSize(void)const;
    virtual void `non-virtual thunk to'BrewingStandgetMaxStackSize(void)const;
    virtual void `non-virtual thunk to'BrewingStandstartOpen(Player &);
    virtual void `non-virtual thunk to'BrewingStandstopOpen(Player &);
    virtual void getSlotCopies(void)const;
    virtual void getSlots(void)const;
    virtual void getItemCount(ItemDescriptor const&);
    virtual void getItemCount(ItemStack const&);
    virtual void findFirstSlotForItem(ItemStack const&)const;
    virtual void `non-virtual thunk to'BrewingStandcanPushInItem(BlockSource &, int, int, ItemInstance const&)const;
    virtual void `non-virtual thunk to'BrewingStandcanPullOutItem(BlockSource &, int, int, ItemInstance const&)const;
    virtual void setContainerChanged(int);
    virtual void setContainerMoved(void);
    virtual void setCustomName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&);
    virtual void hasCustomName(void)const;
    virtual void readAdditionalSaveData(CompoundTag const&);
    virtual void addAdditionalSaveData(CompoundTag &);
    virtual void createTransactionContext(std::function<void ()(Container&, int, ItemStack const&, ItemStack const&)>, std::function<void ()(void)>);
    virtual void triggerTransactionChange(int, ItemStack const&, ItemStack const&);
}
