#pragma once

class EnderChestBlockActor : ChestBlockActor {

    virtual ~EnderChestBlockActor();
    virtual ~EnderChestBlockActor();
    virtual void load(Level &, CompoundTag const&, DataLoadHelper &);
    virtual void save(CompoundTag &)const;
    virtual void saveItemInstanceData(CompoundTag &);
    virtual void saveBlockData(CompoundTag &, BlockSource &)const;
    virtual void loadBlockData(CompoundTag const&, BlockSource &, DataLoadHelper &);
    virtual void onCustomTagLoadDone(BlockSource &);
    virtual void tick(BlockSource &);
    virtual void isFinished(void);
    virtual void onChanged(BlockSource &);
    virtual void isMovable(BlockSource &);
    virtual void isCustomNameSaved(void);
    virtual void getUpdatePacket(BlockSource &);
    virtual void onPlace(BlockSource &);
    virtual void onUpdatePacket(CompoundTag const&, BlockSource &);
    virtual void onMove(void);
    virtual void onRemoved(BlockSource &);
    virtual void triggerEvent(int, int);
    virtual void clearCache(void);
    virtual void onNeighborChanged(BlockSource &, BlockPos const&);
    virtual void getShadowRadius(BlockSource &)const;
    virtual void hasAlphaLayer(void)const;
    virtual void getCrackEntity(BlockSource &, BlockPos const&);
    virtual void getDebugText(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> &, BlockPos const&);
    virtual void _ZNK10BlockActor13getCustomNameB5cxx11Ev;
    virtual void _ZN10BlockActor21getFilteredCustomNameB5cxx11ERK18UIProfanityContext;
    virtual void _ZNK20EnderChestBlockActor7getNameB5cxx11Ev;
    virtual void _ZN10BlockActor22getImmersiveReaderTextB5cxx11ER11BlockSource;
    virtual void getRepairCost(void)const;
    virtual void getOwningPiston(BlockSource &);
    virtual void getContainer(void);
    virtual void getDeletionDelayTimeSeconds(void)const;
    virtual void onChunkLoaded(LevelChunk &);
    virtual void onChunkUnloaded(LevelChunk &);
    virtual void startOpen(Player &);
    virtual void dropContents(BlockSource &, Vec3 const&, bool);
    virtual void getContainerSize(void)const;
    virtual void getMaxStackSize(void)const;
    virtual void getItem(int)const;
    virtual void setItem(int, ItemStack const&);
    virtual void loadItems(CompoundTag const&, Level &);
    virtual void saveItems(CompoundTag &)const;
    virtual void stopOpen(Player &);
    virtual void clearInventory(int);
    virtual void setContainerChanged(int);
    virtual void canPushInItem(BlockSource &, int, int, ItemInstance const&)const;
    virtual void canPullOutItem(BlockSource &, int, int, ItemInstance const&)const;
    virtual void addContentChangeListener(ContainerContentChangeListener *);
    virtual void removeContentChangeListener(ContainerContentChangeListener *);
    virtual void playOpenSound(BlockSource &);
    virtual void playCloseSound(BlockSource &);
    virtual void _canOpenThis(BlockSource &)const;
    virtual void getObstructionAABB(void)const;
    virtual void _detectEntityObstruction(BlockSource &)const;
    virtual void ;
    virtual void `non-virtual thunk to'EnderChestBlockActor::~EnderChestBlockActor();
    virtual void `non-virtual thunk to'EnderChestBlockActor::~EnderChestBlockActor();
    virtual void init(void);
    virtual void `non-virtual thunk to'ChestBlockActor::addContentChangeListener(ContainerContentChangeListener *);
    virtual void `non-virtual thunk to'ChestBlockActor::removeContentChangeListener(ContainerContentChangeListener *);
    virtual void `non-virtual thunk to'ChestBlockActor::getItem(int)const;
    virtual void hasRoomForItem(ItemStack const&);
    virtual void addItem(ItemStack &);
    virtual void addItemToFirstEmptySlot(ItemStack &);
    virtual void `non-virtual thunk to'ChestBlockActor::setItem(int, ItemStack const&);
    virtual void removeItem(int, int);
    virtual void removeAllItems(void);
    virtual void `non-virtual thunk to'RandomizableBlockActorFillingContainer::dropContents(BlockSource &, Vec3 const&, bool);
    virtual void `non-virtual thunk to'ChestBlockActor::getContainerSize(void)const;
    virtual void `non-virtual thunk to'ChestBlockActor::getMaxStackSize(void)const;
    virtual void `non-virtual thunk to'ChestBlockActor::startOpen(Player &);
    virtual void `non-virtual thunk to'ChestBlockActor::stopOpen(Player &);
    virtual void getSlotCopies(void)const;
    virtual void getSlots(void)const;
    virtual void getItemCount(ItemDescriptor const&);
    virtual void getItemCount(ItemStack const&);
    virtual void findFirstSlotForItem(ItemStack const&)const;
    virtual void `non-virtual thunk to'EnderChestBlockActor::canPushInItem(BlockSource &, int, int, ItemInstance const&)const;
    virtual void `non-virtual thunk to'EnderChestBlockActor::canPullOutItem(BlockSource &, int, int, ItemInstance const&)const;
    virtual void `non-virtual thunk to'ChestBlockActor::setContainerChanged(int);
    virtual void setContainerMoved(void);
    virtual void setCustomName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&);
    virtual void hasCustomName(void)const;
    virtual void readAdditionalSaveData(CompoundTag const&);
    virtual void addAdditionalSaveData(CompoundTag &);
    virtual void createTransactionContext(std::function<void ()(Container&, int, ItemStack const&, ItemStack const&)>, std::function<void ()(void)>);
    virtual void triggerTransactionChange(int, ItemStack const&, ItemStack const&);
    virtual void add(ItemStack &);
    virtual void canAdd(ItemStack const&)const;
    virtual void dropAll(bool);
    virtual void clearSlot(int);
    virtual void `non-virtual thunk to'ChestBlockActor::clearInventory(int);
    virtual void load(ListTag const&, SemVersion const&, Level &);
    virtual void doDrop(ItemStack &, bool);
    virtual void getEmptySlotsCount(void)const;
}
