#pragma once

#include "../../unmapped/ActionEvent.h"
#include "unmapped/ActorRuntimeID.h"
#include "unmapped/ActorUniqueID.h"
#include <memory>
#include <vector>
#include <string>
#include "../util/BlockPos.h"
#include <functional>
#include "../util/Vec3.h"


class Actor {

public:
    static long TOTAL_AIR_SUPPLY;
    static long DAMAGE_NEARBY_MOBS_DURATION;
    static long DEFAULT_AMBIENT_SOUND_INTERVAL;
    static long DEFAULT_AMBIENT_SOUND_INTERVAL_RANGE;
    static std::string RIDING_TAG;

//  virtual void playSynchronizedSound(LevelSoundEvent, Vec3 const&, Block const&, bool); //TODO: incomplete function definition
    virtual void save(CompoundTag &);
    virtual void getInventorySize()const;
    virtual void getDefaultLootTable();
    virtual bool isSleeping()const;
    virtual void getAlwaysShowNameTag()const;
    virtual bool isAdventure()const;
//  virtual void setArmor(ArmorSlot, ItemStack const&); //TODO: incomplete function definition
//  virtual void setEquippedSlot(ArmorSlot, ItemStack const&); //TODO: incomplete function definition
//  virtual void getExitTip(std::string const&, InputMode)const; //TODO: incomplete function definition
    virtual void setStanding(bool);
    virtual void tryTeleportTo(Vec3 const&, bool, bool, int, int);
    virtual void loadLinks(CompoundTag const&, std::vector<ActorLink> &, DataLoadHelper &);
    virtual void getInteraction(Player &, ActorInteraction &, Vec3 const&);
    virtual std::string getFormattedNameTag()const;
    virtual bool canChangeDimensions()const;
    virtual void _doAutoAttackOnTouch(Actor &);
    virtual bool isDamageBlocked(ActorDamageSource const&)const;
    virtual void interactPreventDefault();
    virtual bool canSynchronizeNewEntity()const;
    virtual void setAuxValue(int);
    virtual void checkInsideBlocks(float);
    virtual void checkBlockCollisions();
//  virtual void getAttachPos(ActorLocation, float)const; //TODO: incomplete function definition
    virtual void onFailedTame();
    virtual void startRiding(Actor &);
    virtual void getYawSpeedInDegreesPerSecond()const;
    virtual bool isCreative()const;
//  virtual void getArmorMaterialTextureTypeInSlot(ArmorSlot)const; //TODO: incomplete function definition
    virtual void getOutputSignal()const;
    virtual void stopSpinAttack();
    virtual void setSize(float, float);
    virtual void getLifeSpan()const;
    virtual void onEffectUpdated(MobEffectInstance const&);
    virtual void addRider(Actor &);
    virtual void onSynchedDataUpdate(int);
    virtual bool isOverWater()const;
    virtual void actuallyHurt(int, ActorDamageSource const*, bool);
    virtual void onAboveBubbleColumn(bool);
    virtual void getChestSlots()const;
    virtual void getEquipmentCount()const;
    virtual void checkBlockCollisions(AABB const&);
    virtual bool hasEnteredWater()const;
    virtual bool isTargetable()const;
    virtual bool isInWall()const;
    virtual void killed(Actor &);
    virtual void rideLanded(Vec3 const&, Vec3 const&);
    virtual void getRiderYRotation(Actor const&)const;
    virtual void getSourceUniqueID()const;
    virtual void teleportTo(Vec3 const&, bool, int, int);
    virtual void getFiringPos()const;
//  virtual void reloadComponents(Actor::InitializationMethod, VariantParameterList const&); //TODO: incomplete function definition
    virtual void intersects(Vec3 const&, Vec3 const&)const;
    virtual void setSneaking(bool);
    virtual void getEntityTypeId()const;
    virtual void shouldRender()const;
    virtual void performRangedAttack(Actor &, float);
    virtual void setOnFire(int);
    virtual void _makeFlySound()const;
//  virtual void setEquippedSlot(ArmorSlot, int, int); //TODO: incomplete function definition
    virtual void makeStuckInBlock(float);
    virtual bool canSee(Vec3 const&)const;
    virtual void awardKillScore(Actor &, int);
    virtual void getMutableAttribute(Attribute const&);
    virtual bool canMakeStepSound()const;
//  virtual void getArmor(ArmorSlot)const; //TODO: incomplete function definition
    virtual void heal(int);
    virtual bool isInWater()const;
    virtual std::string getScoreTag()const;
    virtual bool isImmobile()const;
    virtual void rideJumped();
    virtual bool isBlocking()const;
    virtual bool isValidTarget(Actor *)const;
    virtual bool isLeashableType();
    virtual void die(ActorDamageSource const&);
    virtual bool isAlive()const;
    virtual bool isInWaterOrRain()const;
    virtual void _playFlySound(BlockPos const&, Block const&);
    virtual void getNameTagAsHash()const;
    virtual std::string getNameTag()const;
//  virtual void getArmorColorInSlot(ArmorSlot, int)const; //TODO: incomplete function definition
    virtual void stopRiding(bool, bool, bool);
    virtual void wobble();
    virtual void reloadLootTable();
    virtual void _removeRider(ActorUniqueID const&, bool, bool);
    virtual bool canSee(Actor const&)const;
    virtual void blockedByShield(ActorDamageSource const&, Actor &);
    virtual bool isInvisible()const;
    virtual void spawnAtLocation(Block const&, int, float);
//  virtual void reloadHardcodedClient(Actor::InitializationMethod, VariantParameterList const&); //TODO: incomplete function definition
    virtual void normalTick();
    virtual void setNameTag(std::string const&);
    virtual bool isSurfaceMob()const;
    virtual void setTarget(Actor *);
    virtual bool canAttack(Actor *, bool)const;
    virtual bool isCreativeModeAllowed();
    virtual void getInterpolatedRidingOffset(float)const;
    virtual void getAttribute(Attribute const&)const;
    virtual void markHurt();
    virtual bool isSilent();
    virtual void inCaravan()const;
//  virtual void reloadHardcoded(Actor::InitializationMethod, VariantParameterList const&); //TODO: incomplete function definition
    virtual void feed(int);
    virtual void onOrphan();
    virtual void reloadLootTable(EquipmentTableDescription const*);
    virtual void getInterpolatedBodyRot(float)const;
    virtual bool canSeeInvisible()const;
    virtual void getCommandPermissionLevel()const;
    virtual void findAttackTarget();
    virtual bool canBeAffectedByArrow(MobEffectInstance const&)const;
    virtual bool isInLava()const;
//  virtual void useItem(ItemStack &, ItemUseMethod, bool); //TODO: incomplete function definition
    virtual bool breaksFallingBlocks()const;
    virtual bool canBeAffected(MobEffectInstance const&)const;
    virtual bool isWorldBuilder();
    virtual void getYHeadRot()const;
    virtual bool isShootable();
    virtual void openContainerComponent(Player &);
    virtual void addAdditionalSaveData(CompoundTag &);
    virtual void spawnAtLocation(int, int, float);
    virtual void getInterpolatedWalkAnimSpeed(float)const;
    virtual void stopSwimming();
//  virtual void playSynchronizedSound(LevelSoundEvent, Vec3 const&, int, bool); //TODO: incomplete function definition
    virtual bool canDestroyBlock(Block const&)const;
    virtual void getPos()const;
    virtual void playerTouch(Player &);
    virtual void getPortalWaitTime()const;
    virtual void getPortalCooldown()const;
    virtual void readAdditionalSaveData(CompoundTag const&, DataLoadHelper &);
//  virtual void renderDebugServerState(Options const&); //TODO: incomplete function definition
    virtual bool isEnchanted()const;
    virtual bool hasOutputSignal(unsigned char)const;
    virtual void setRot(Vec2 const&);
    virtual bool isOnHotBlock()const;
    virtual void getEquipSlots()const;
    virtual void handleInsidePortal(BlockPos const&);
    virtual void swing();
//  virtual bool isUnderLiquid(MaterialType)const; //TODO: incomplete function definition
    virtual void getShadowRadius()const;
    virtual void getInterpolatedHeadRot(float)const;
    virtual void getCarriedItem()const;
    virtual void queryEntityRenderer()const;
    virtual bool isInvulnerableTo(ActorDamageSource const&)const;
    virtual void spawnAtLocation(int, int);
    virtual void getPickRadius();
    virtual bool isFree(Vec3 const&, float);
    virtual bool isPickable();
    virtual void causeFallDamage(float);
//  virtual void initializeComponents(Actor::InitializationMethod, VariantParameterList const&); //TODO: incomplete function definition
    virtual bool canExistInPeaceful()const;
    virtual void getAnimationComponent();
    virtual void spawnTrailBubbles();
    virtual bool isSkyLit(float);
    virtual bool isInvertedHealAndHarm()const;
    virtual void setCarriedItem(ItemStack const&);
    virtual void consumeTotem();
    virtual void updateWaterState();
    virtual void getHeadLookVector(float);
    virtual void filterFormattedNameTag(UIProfanityContext const&);
    virtual void rideTick();
    virtual void setNameTagVisible(bool);
    virtual bool isSneaking()const;
    virtual void getDeathTime()const;
    virtual void kill();
    virtual void getAddPacket();
    virtual bool hasComponent(Util::HashString const&)const;
    virtual void outOfWorld();
    virtual void getLootTable();
    virtual void positionRider(Actor &, float);
    virtual void setPos(Vec3 const&);
    virtual void pushOutOfBlocks(Vec3 const&);
    virtual void lerpTo(Vec3 const&, Vec2 const&, int);
    virtual void tickLeash();
    virtual bool isFree(Vec3 const&);
    virtual void getRidingHeight();
    virtual void saveWithoutId(CompoundTag &);
    virtual void reset();
    virtual void changeDimension(ChangeDimensionPacket const&);
    virtual void doWaterSplashEffect();
    virtual void startSpinAttack();
    virtual void startSwimming();
    virtual bool isOnFire()const;
    virtual void onEffectRemoved(MobEffectInstance &);
    virtual void setScoreTag(std::string const&);
    virtual void move(Vec3 const&);
    virtual void buildDebugInfo(std::string &)const;
    virtual void updateEntitySpecificMolangVariables(RenderParams &);
    virtual void setOwner(ActorUniqueID);
    virtual void getShadowHeightOffs();
    virtual void spawnAtLocation(ItemStack const&, float);
    virtual bool canPowerJump()const;
    virtual void getDeletionDelayTimeSeconds()const;
    virtual void getDimensionId()const;
    virtual void flagRiderToRemove(Actor &);
    virtual void drop(ItemStack const&, bool);
    virtual void onBounceStarted(BlockPos const&, Block const&);
    virtual void remove();
    ~Actor();
    virtual void baseTick();
    virtual void doFireHurt(int);
    virtual void onLightningHit();
    virtual void getControllingPlayer()const;
    virtual void getMapDecorationRotation()const;
    virtual void add(ItemStack &);
    virtual void getPosExtrapolated(float)const;
    virtual void onTame();
    virtual void spawnAtLocation(Block const&, int);
//  virtual void changeDimension(AutomaticID<Dimension, int>, bool); //TODO: incomplete function definition
    virtual void handleFallDistanceOnServer(float, bool);
    virtual void sendMotionPacketIfNeeded();
    virtual void getOnDeathExperience();
//  virtual void getArmorMaterialTypeInSlot(ArmorSlot)const; //TODO: incomplete function definition
    virtual void getEquippedTotem()const;
    virtual bool wasHurt();
    virtual void animateHurt();
    virtual void getInterpolatedRidingPosition(float)const;
    virtual bool isJumping()const;
    virtual void adjustDamageAmount(int &)const;
    virtual void setOffhandSlot(ItemStack const&);
    virtual bool canAddRider(Actor &)const;
    virtual void moveRelative(float, float, float, float);
    virtual void setSitting(bool);
    virtual void getDebugText(std::vector<std::string> &);
    virtual void shouldTick()const;
    virtual void _onSizeUpdated();
    virtual void lerpMotion(Vec3 const&);
    virtual void setCanPowerJump(bool);
    virtual bool isFishable()const;
    virtual void getOwnerEntityType();
    virtual bool canShowNameTag()const;
    virtual bool chorusFruitTeleport(Vec3 &);
    virtual void _playStepSound(BlockPos const&, Block const&);
    virtual void despawn();
    virtual void getPosOld()const;
    virtual bool isImmersedInWater()const;
    virtual void load(CompoundTag const&, DataLoadHelper &);
    virtual void setDamageNearbyMobs(bool);
//  virtual void handleEntityEvent(ActorEvent, int); //TODO: incomplete function definition
    virtual void updateInsideBlock();
    virtual void onInsideBubbleColumn(bool);
    virtual void getHandleWaterAABB()const;
    virtual void getBrightness(float)const;
    virtual void getCameraOffset()const;
    virtual void _hurt(ActorDamageSource const&, int, bool, bool);
    virtual void attack(Actor &);
    virtual void checkFallDamage(float, bool);
    virtual void onEffectAdded(MobEffectInstance &);
    virtual bool canBePulledIntoVehicle()const;
    virtual void getInterpolatedBodyYaw(float)const;
    virtual bool canBeAffected(int)const;
    void removePersistingTrade();
    void getTargetId();
    void setScared(bool);
    bool isInSnow()const;
    bool isAutoSendEnabled()const;
//  void _setActorTypeId(ActorType); //TODO: incomplete function definition
    bool hasLevel()const;
    void setEnchanted(bool);
    bool isIgnited()const;
    void _setupServerAnimationComponent();
    void distanceTo(Actor const&)const;
    void setShakeTime(int);
    void getLevel()const;
    void updateDescription();
    void getOwnerId()const;
    void setTradingPlayer(Player *);
    void removeDefinitionGroup(std::string const&);
    bool isUnderWaterfall()const;
    void pullInEntity(Actor &);
    void loadEntityFlags(CompoundTag const&, DataLoadHelper &);
    void teleportRidersTo(Vec3 const&, int, int);
    void _serializeComponents(CompoundTag &);
//  void playSound(LevelSoundEvent, Vec3 const&, Block const&); //TODO: incomplete function definition
    void shouldOrphan(BlockSource &);
    bool canClimb()const;
    void sendActorDefinitionEventTriggered(std::string const&);
    void getStateVectorComponent()const;
    void createUpdateTradePacket(int);
    bool wasLastHitByPlayer();
    void setLastHitBB(Vec3 const&, Vec3 const&);
    bool isWithinRestriction(BlockPos const&)const;
    void getViewVector2(float)const;
    void _randomHeartPos();
    bool isBribed()const;
    void clearActionQueue();
    void getDimensionConst()const;
    void lovePartnerId()const;
    void setCharged(bool);
    bool isRegionValid()const;
    bool isTrading()const;
    bool isInClouds()const;
    bool isExperimental()const;
    void setPosDirectLegacy(Vec3 const&);
    void _setPosPrev(Vec3 const&);
    void spawnEatParticles(ItemStack const&, int);
    bool isChested()const;
    void setBlockTarget(BlockPos const&);
    bool isClimbing()const;
    void setCanFly(bool);
    void updateBBFromDescription();
    void getHurtDir()const;
    void getRotation()const;
    void _spawnPukeParticles();
    bool hasFamily(Util::HashString const&)const;
    bool isLeashed()const;
    void getAmbientSoundEvent()const;
    bool isRiding()const;
    void setControllingSeat(int);
    bool hasPriorityAmmunition()const;
    void _setHeightOffset(float);
    void calculateAttackDamage(Actor &);
    void getMolangVariables();
    void setDancing(bool);
    void saveLinks()const;
    void migrateUniqueID(ActorUniqueID);
//  void fetchNearbyActorsSorted(Vec3 const&, ActorType); //TODO: incomplete function definition
    bool isInPrecipitation()const;
    bool hasExcessFood();
    void setResting(bool);
    bool isInRain()const;
    Actor(Level &);
    void setStructuralIntegrity(int);
    bool hasRestriction()const;
    void getAmbientSoundIntervalMin(float &)const;
    bool isPowered()const;
    void getPlayerOwner()const;
    void getSlotAllowedItems(int);
    void setStrengthMax(int);
    void setBaseDefinition(ActorDefinitionIdentifier const&, bool, bool);
    void getHurtTime()const;
    void setVariant(int);
    void getHandContainer()const;
    void setInLove(Actor *);
    void getViewVector(float)const;
    bool isClient()const;
    void getArmorContainer()const;
    void getRideRoot()const;
    void getSpatialNetworkData()const;
    void buildForward()const;
    void _getAABBShapeComponentNonConst();
    void _containsSneakCollisionShapes(AABB const&);
    void reload();
    std::string getTags()const;
    void burn(int, bool);
    void testForEntityStacking(BlockSource &, AABB const&, std::vector<AABB> &);
    void setPreviousPosRot(Vec3 const&, Vec2 const&);
    bool isSwimmer()const;
    void removeTag(std::string const&);
    void getDamageNearbyMobs()const;
    void getJumpDuration()const;
    void getRestrictCenter()const;
    bool hasAnyVisibleEffects()const;
    bool isDelayedAttacking()const;
    void updateTickingData();
    void onOnewayCollision(BlockPos);
    bool isDoorOpener()const;
//  void setColor(PaletteColor); //TODO: incomplete function definition
    bool isInWorld()const;
//  bool hasAttributeBuff(AttributeBuffType)const; //TODO: incomplete function definition
    void getEntity()const;
    void setLeashHolder(ActorUniqueID);
    bool isStanding()const;
    void setWalker(bool);
    void getCenter(float)const;
    void spawnDeathParticles();
//  void getStatusFlag(ActorFlags)const; //TODO: incomplete function definition
    bool hasTickingArea()const;
    void removeEffect(int);
    void transferTickingArea(Dimension &);
    void serializationSetHealth(int);
    void deregisterTagsFromLevelCache();
    void getDimension()const;
    void setUniqueID(ActorUniqueID);
    void removeEffectNoUpdate(int);
    void setDelayedAttacking(bool);
    void getStrength()const;
    void _getLevelPtr()const;
    void cacheComponentData();
    bool canCurrentlySwim()const;
    void getTradingPlayer()const;
    Actor(ActorDefinitionGroup *, ActorDefinitionIdentifier const&);
    void dropLeash(bool, bool);
    void getCollidableMobNear();
    void getPersistingTradeRiches();
    void setRuntimeID(ActorRuntimeID);
    void getUniqueID()const;
    void _getStateVectorComponentNonConst();
    bool hasPersistingTrade()const;
    void onLadder(bool)const;
    void dropTowards(ItemStack const&, Vec3);
    void setJumpDuration(int);
    void pushBackActionEventToActionQueue(ActionEvent);
    void getVariant()const;
    void getRandomPointInAABB(Random &);
    void _getTallestCollisionShape(AABB const&, AABB const&, Vec3 const&);
    bool isAngry()const;
    bool canFly()const;
    bool hasSaddle()const;
    bool hasUniqueID()const;
    void getOffhandSlot()const;
    void _manageRiders(BlockSource &);
    void testForCollidableMobs(BlockSource &, AABB const&, std::vector<AABB> &);
    void positionAllRiders();
    void setGlobal(bool);
    void resetClientAnimations();
    void fetchFishingHook();
    void doEnchantDamageEffects(Mob &, Mob &);
    bool isInThunderstorm()const;
    void getRegionConst()const;
    void _updateOnewayCollisions(BlockSource &);
    void _exitRide(Actor const&, float);
    bool isTickingEntity()const;
    void getAirSupply()const;
    bool hasRider()const;
    void sendMotionToServer();
    void setHurtDir(int);
    void getSpeedInMetersPerSecond()const;
    void onOnewayCollision(AABB const&);
    void _spawnTreasureHuntingParticles();
    void getStateVectorComponentNonConst();
    void getEffect(MobEffect const&)const;
    void getRide()const;
    void checkEntityOnewayCollision(BlockSource &, BlockPos const&);
    bool isInsidePortal();
    bool isResting()const;
    bool isRider(ActorUniqueID const&)const;
    void setBreakingObstruction(bool);
//  bool hasType(ActorType)const; //TODO: incomplete function definition
    bool isOverScaffolding()const;
    void removeEntity();
    bool isDancing()const;
    void updateBBFromDescription(CollisionBoxDescription const&);
    bool isDoorBreaker()const;
    void updateInBubbleColumnState();
    void clearRestriction();
    void _tryPlaceAt(Vec3 const&);
    bool canOpenContainer(Player &)const;
    bool hasTags()const;
    void setWASDControlled(bool);
    void saveEntityFlags(CompoundTag &);
    bool hasEffect(MobEffect const&)const;
    void getStrengthMax()const;
    void getEntityTerrainInterlockData();
    void updateMolangVariables(RenderParams &);
    void getColor()const;
    void getRestrictRadius()const;
    void getStructuralIntegrity()const;
    void _setAABB(AABB const&);
    void setDoorBreaker(bool);
    void setInvisible(bool);
    void getColor2()const;
    void _damageNearbyMobs();
    bool isControlledByLocalInstance()const;
    void setCanClimb(bool);
    void getHurtColor()const;
    bool isInitialized();
    bool isOrphan()const;
    void getFirstRider()const;
    void setCollidableMob(bool);
    void setLimitedLife(int);
    void getTradeInterest()const;
    void _setAABBDim(Vec2 const&);
    bool isSheared()const;
    bool hasDefinitionGroup(std::string const&)const;
    void getRadius()const;
    bool isSafeToSleepNear()const;
    void setPersistent();
    void moveChunks();
    void getNextActionEvent(ActionEvent &);
    void removeAllRiders(bool, bool);
    void removeEffectParticles();
    bool isTrusting()const;
    void setSkinID(int);
    void getShakeTime()const;
    bool isRider(Actor const&)const;
    void setPosPrev(Vec3 const&);
    bool isRiding(Actor *)const;
    void resetRegion();
    void getHealth()const;
    void setMoving(bool);
    void setEnforceRiderRotationLimit(bool);
    bool canMate(Actor const&)const;
    bool isGlobal()const;
    void getAttributes();
    void getAllEffects()const;
    void getMarkVariant()const;
    bool isWASDControlled();
    bool wantsMoreFood();
    void _setLevelPtr(Level *);
    void initParams(VariantParameterList &);
    void setChanged();
    bool isScared()const;
    void clearFishingHookID();
    void initEntity(EntityRegistryOwned &);
    void getCollidableMob();
    void calcCenterPos()const;
    void refreshComponents();
    void addTag(std::string const&);
    void setOffersFromPacket(UpdateTradePacket const&);
    void getSwimAmount(float)const;
    void getChainedDamageEffects()const;
    bool isTame()const;
    bool canBeginOrContinueClimbingLadder(bool)const;
    bool hasTotemEquipped()const;
    void setEquipFromPacket(UpdateEquipPacket const&);
    bool isInsideBorderBlock(float)const;
    void getTradeOffers();
    void restrictTo(BlockPos const&, float);
    void setChainedDamageEffects(bool);
    void setSaddle(bool);
    void getHandContainer();
    bool isAutonomous()const;
    void savePersistingTrade(std::unique_ptr<CompoundTag>, int);
    void healEffects(int);
    void distanceToSqr(Vec3 const&)const;
    void setLayingDown(bool);
    bool isMoving()const;
    void setSeatDescription(Vec3 const&, SeatDescription const&);
    void moveBBs(Vec3 const&);
    void getAABBShapeComponent()const;
    void _getBlockOnPos();
    void setAutonomous(bool);
    bool isLayingDown()const;
    bool isRemoved()const;
    void _countFood(int);
    void onChunkDiscarded();
    void getRegion()const;
    bool hasTeleported()const;
    void spawnBalloonPopParticles();
    void getControllingSeat();
//  bool hasCategory(ActorCategory)const; //TODO: incomplete function definition
    void getPersistingTradeOffers();
    void getRenderLeashHolder();
    void getOwner()const;
    void getCurrentSwimAmount()const;
    void getTickingArea();
    bool isWithinRestriction()const;
    void getActiveEffectCount()const;
    void hurt(ActorDamageSource const&, int, bool, bool);
    bool hasEnoughFoodToBreed();
    void setMarkVariant(int);
    void getPortalEntranceAxis()const;
    void executeEvent(std::string const&, VariantParameterList const&);
    void _initializeLeashRopeSystem();
    bool isInLove()const;
    bool isSwimming()const;
    bool hasSubBBInLava()const;
    void getEntity();
    void setClimbing(bool);
    void getInterpolatedRotation(float)const;
    void getRuntimeID()const;
    bool isSitting()const;
    void _refreshAABB();
    void setStrength(int);
    void tick(BlockSource &);
    void spawnTamingParticles(bool);
    void enforceRiderRotationLimit()const;
    void getAmbientSoundIntervalRange(float &)const;
    void getTarget()const;
    void setSwimmer(bool);
    void getFirstAvailableSeatPos(Actor &, Vec3 &)const;
    void getTempted()const;
    void getLinks()const;
    void getMaxHealth()const;
    void getRandom()const;
    bool isActionQueueEmpty()const;
    void getSpatialNetworkData();
    void spawnDustParticles(int);
    bool isInScaffolding()const;
    void getEntityData()const;
    void setCollidableMobNear(bool);
    void distanceSqrToBlockPosCenter(BlockPos const&)const;
    void moveTo(Vec3 const&, Vec2 const&);
    void requireReload();
    void getLevel();
    void getLeashHolder()const;
    void _tryPlantWitherRose();
    bool hasFishingHook()const;
    void buildDebugGroupInfo(std::string &)const;
    void _isValidBlockToTeleportOnto(Block const&, bool)const;
    void setFishingHookID(ActorUniqueID);
    void getBlockTarget()const;
    bool hasTag(std::string const&)const;
    void setHurtTime(int);
    void setAABBDim(Vec2 const&);
    void getActorIdentifier()const;
    void enableAutoSendPosRot(bool);
    void _setDimension(Dimension &);
    void setTempted(bool);
    void getRiderIndex(Actor &)const;
    void setDoorOpener(bool);
    void _playMovementSound(bool);
    void getActorToWorldTransform(float, bool, Vec3 const&)const;
    bool hasRuntimeID()const;
    void setRegion(BlockSource &);
    void forEachLeashedActor(std::function<void (Actor *)>);
    void addDefinitionGroup(std::string const&);
    void getRideRuntimeID()const;
    void createUpdateEquipPacket(int);
    void updateInvisibilityStatus();
    void getArmorContainer();
    void setExperimental(bool);
    void pickUpItem(ItemActor &, int);
    void getSkinID()const;
    void getEconomyTradeableComponent()const;
    bool isCharged()const;
    bool isFireImmune()const;
    void operator==(Actor &);
    void _convertOldSave(CompoundTag const&);
    void getLocator(HashedString const&);
    void _updateOwnerChunk();
    void pickUpItem(ItemActor &);
    void distanceToSqr(Actor const&)const;
    bool isBreakingObstruction()const;
    void getTotalAirSupply()const;
    bool isBaby()const;
//  void setColor2(PaletteColor); //TODO: incomplete function definition
    void getEntityData();
    void getInterpolatedPosition(float)const;
    bool isStackable()const;
//  void _setNetherPortalData(AutomaticID<Dimension, int>, AutomaticID<Dimension, int>, int); //TODO: incomplete function definition
    void setPowered(bool);
    void addEffect(MobEffectInstance const&);
    void getVerticalSpeedInMetersPerSecond()const;
    void _sendDirtyActorData();
    void removeAllEffects();
    void _sendLinkPacket(ActorLink const&)const;
    bool isDebugging()const;
//  void playSound(LevelSoundEvent, Vec3 const&, int); //TODO: incomplete function definition
    bool hasAnyEffects()const;
    void distanceTo(Vec3 const&)const;
    void getInitializationMethod();
    bool isWalker()const;
    void reloadIfRequired();
    bool hasEntity()const;
    bool hasPlayerRider()const;
    bool isPersistent()const;
//  void setStatusFlag(ActorFlags, bool); //TODO: incomplete function definition
    void setTradeInterest(bool);
    void _defaultInitEquipmentDropChances();
    void _setPos(Vec3 const&);
};
