#pragma once

#include <string>
#include "../util/Brightness.h"
#include <vector>
#include <functional>


class BlockLegacy {

public:
    static long SIZE_OFFSET;
    static std::string BLOCK_DESCRIPTION_PREFIX;

    virtual std::string buildDescriptionId(Block const&)const;
    virtual bool isSeasonTinted(Block const&, BlockSource &, BlockPos const&)const;
    virtual void setExplodeable(float);
    virtual void onFillBlock(BlockSource &, BlockPos const&, Block const&)const;
    virtual void getExplosionResistance(Actor *)const;
    virtual void onExploded(BlockSource &, BlockPos const&, Actor *)const;
    virtual bool isButtonBlock()const;
    virtual bool isWaterBlocking()const;
    virtual void getResourceCount(Random &, Block const&, int)const;
    virtual void telemetryVariant(BlockSource &, BlockPos const&)const;
    virtual void onRedstoneUpdate(BlockSource &, BlockPos const&, int, bool)const;
    virtual bool isAttachedTo(BlockSource &, BlockPos const&, BlockPos &)const;
    virtual void ignoreEntitiesOnPistonMove(Block const&)const;
    virtual void addAABBs(Block const&, BlockSource &, BlockPos const&, AABB const*, std::vector<AABB> &)const;
    virtual bool isStrippable(Block const&)const;
    virtual void playerDestroy(Player &, BlockPos const&, Block const&)const;
    virtual void getFaceFlip(unsigned char, Block const&)const;
    virtual void getIconYOffset()const;
    virtual void getVisualShape(Block const&, AABB &, bool)const;
    virtual bool canBeUsedInCommands(bool, BaseGameVersion const&)const;
    virtual void setLightBlock(Brightness);
    virtual void getCollisionShape(AABB &, Block const&, BlockSource &, BlockPos const&, Actor *)const;
    virtual bool isHurtableBlock()const;
    virtual void attack(Player *, BlockPos const&)const;
    virtual void mayConsumeFertilizer(BlockSource &)const;
    virtual void getAABB(BlockSource &, BlockPos const&, Block const&, AABB &, bool)const;
    virtual void setupRedstoneComponent(BlockSource &, BlockPos const&)const;
    virtual void getVariant(Block const&)const;
    virtual void checkIsPathable(Actor &, BlockPos const&, BlockPos const&)const;
    virtual void liquidCanFlowIntoFromDirection(unsigned char, std::function<Block const& (BlockPos const&)> const&, BlockPos const&)const;
    virtual void init();
    virtual void getStateFromLegacyData(unsigned short)const;
    virtual bool isDoorBlock()const;
    virtual bool canContainLiquid()const;
    virtual bool detachesOnPistonMove(BlockSource &, BlockPos const&)const;
    virtual void getLightEmission(Block const&)const;
    virtual void sanitizeFillBlock(BlockSource &, BlockPos const&, Block const&)const;
    virtual bool breaksFallingBlocks(Block const&)const;
    virtual void getExperienceDrop(Random &)const;
    virtual void shouldRandomTick()const;
    virtual bool isStairBlock()const;
    virtual bool isBounceBlock()const;
    virtual void getPlacementBlock(Actor &, BlockPos const&, unsigned char, Vec3 const&, int)const;
    virtual void getMobToSpawn(SpawnConditions const&, BlockSource &)const;
    virtual bool canSpawnOn()const;
    virtual void getNextBlockPermutation(Block const&)const;
    virtual void getIgnoresDestroyPermissions(Actor &, BlockPos const&)const;
    virtual void handleRain(BlockSource &, BlockPos const&, float)const;
    virtual bool hasVariableLighting()const;
    virtual void getUIShape(Block const&, AABB &)const;
    virtual void getStrippedBlock(Block const&)const;
    virtual void mayPick()const;
    virtual void calcVariant(BlockSource &, BlockPos const&)const;
    virtual void clip(BlockSource &, BlockPos const&, Vec3 const&, Vec3 const&, bool)const;
    virtual void waterSpreadCausesSpawn()const;
    virtual void getMapColor()const;
    virtual bool canBeOriginalSurface()const;
    virtual void entityInside(BlockSource &, BlockPos const&, Actor &)const;
    virtual bool isAuxValueRelevantForPicking()const;
    virtual void mayPlace(BlockSource &, BlockPos const&, unsigned char)const;
    virtual void onProjectileHit(BlockSource &, BlockPos const&, Actor const&)const;
    virtual void shouldConnectToRedstone(BlockSource &, BlockPos const&, int)const;
    virtual bool canHaveExtraData()const;
    virtual void getExtraRenderLayers()const;
    virtual void mayPlace(BlockSource &, BlockPos const&)const;
//  virtual void onFertilized(BlockSource &, BlockPos const&, Actor *, FertilizerType)const; //TODO: incomplete function definition
    virtual bool isValidAuxValue(int)const;
    virtual void dispense(BlockSource &, Container &, int, Vec3 const&, unsigned char)const;
    virtual bool isRailBlock()const;
    virtual void spawnBurnResources(BlockSource &, float, float, float)const;
    virtual void getShadeBrightness()const;
    virtual bool canSlide(BlockSource &, BlockPos const&)const;
    virtual void getRenderLayer(Block const&, BlockSource &, BlockPos const&)const;
    virtual void addState(ItemState const&, unsigned long);
    virtual void getThickness()const;
    virtual void onStepOn(Actor &, BlockPos const&)const;
    virtual void neighborChanged(BlockSource &, BlockPos const&, BlockPos const&)const;
    virtual void getFlexibility(BlockSource &, BlockPos const&)const;
    virtual void triggerEvent(BlockSource &, BlockPos const&, int, int)const;
    virtual void setAllowsRunes(bool);
    virtual void getColor(Block const&)const;
    virtual bool isCraftingBlock()const;
    virtual bool canBeBuiltOver(BlockSource &, BlockPos const&)const;
    virtual void getVisualShapeInWorld(Block const&, BlockSource &, BlockPos const&, AABB &, bool)const;
    virtual bool isWallBlock()const;
    virtual void getRedstoneProperty(BlockSource &, BlockPos const&)const;
    virtual void calcGroundFriction(Mob &, BlockPos const&)const;
    virtual void animateTick(BlockSource &, BlockPos const&, Random &)const;
    virtual void randomlyModifyPosition(BlockPos const&)const;
    virtual bool canHurtAndBreakItem()const;
    virtual void getColor(BlockSource &, BlockPos const&, Block const&)const;
    virtual void getSecondPart(BlockSource &, BlockPos const&, BlockPos &)const;
    virtual void executeEvent(BlockSource &, BlockPos const&, Block const&, std::string const&, Actor &)const;
    virtual bool isCropBlock()const;
    virtual bool isInteractiveBlock()const;
    virtual void mayPick(BlockSource &, Block const&, bool)const;
    virtual void onRemove(BlockSource &, BlockPos const&)const;
    virtual void mayPlaceOn(BlockSource &, BlockPos const&)const;
    virtual void getResourceItem(Random &, Block const&, int)const;
    virtual void getColorAtPos(BlockSource &, BlockPos const&)const;
    virtual bool canFillAtPos(BlockSource &, BlockPos const&, Block const&)const;
    virtual void tryLegacyUpgrade(unsigned short)const;
    virtual void tick(BlockSource &, BlockPos const&, Random &)const;
    virtual void onFallOn(BlockSource &, BlockPos const&, Actor *, float)const;
    virtual void getLiquidClipVolume(BlockSource &, BlockPos const&, AABB &)const;
    virtual void getComparatorSignal(BlockSource &, BlockPos const&, Block const&, unsigned char)const;
    virtual bool isSignalSource()const;
    virtual bool isObstructingChests(BlockSource &, BlockPos const&)const;
    virtual bool isThinFenceBlock()const;
    virtual void shouldDispense(BlockSource &, Container &)const;
    virtual void setLightEmission(float);
    virtual void updateEntityAfterFallOn(Actor &)const;
//  virtual bool canProvideSupport(Block const&, unsigned char, BlockSupportType)const; //TODO: incomplete function definition
    virtual bool isContainerBlock()const;
    virtual void onMove(BlockSource &, BlockPos const&, BlockPos const&)const;
    virtual void getSilkTouchItemInstance(Block const&)const;
    virtual bool asItemInstance(BlockSource &, BlockPos const&, Block const&)const;
    virtual void getConnectedDirections(Block const&, BlockPos const&, BlockSource &, bool &, bool &, bool &, bool &)const;
    virtual void addCollisionShapes(Block const&, BlockSource &, BlockPos const&, AABB const*, std::vector<AABB> &, Actor *)const;
    virtual bool canSurvive(BlockSource &, BlockPos const&)const;
    virtual bool canConnect(Block const&, unsigned char, Block const&)const;
    virtual void getColorForParticle(BlockSource &, BlockPos const&, Block const&)const;
    virtual bool isStemBlock()const;
    virtual bool isSlabBlock()const;
    virtual void spawnResources(BlockSource &, BlockPos const&, Block const&, float, int)const;
    virtual void getOutline(BlockSource &, BlockPos const&, AABB &)const;
    virtual void onPlace(BlockSource &, BlockPos const&)const;
    virtual void shouldStopFalling(Actor &)const;
    virtual void destroy(BlockSource &, BlockPos const&, Block const&, Actor *)const;
    virtual void transformOnFall(BlockSource &, BlockPos const&, Actor *, float)const;
    virtual bool hasTag(BlockSource &, BlockPos const&, Block const&, std::string const&)const;
    virtual bool canBeSilkTouched()const;
    virtual void onGraphicsModeChanged(bool, bool, bool);
    virtual void playerWillDestroy(Player &, BlockPos const&, Block const&)const;
    virtual void addState(ItemState const&);
    virtual void setVisualShape(Vec3 const&, Vec3 const&);
    virtual void use(Player &, BlockPos const&)const;
    virtual void getDirectSignal(BlockSource &, BlockPos const&, int)const;
    virtual void getRenderLayer()const;
    virtual bool dealsContactDamage(Actor const&, Block const&, bool)const;
    ~BlockLegacy();
    virtual bool isFenceGateBlock()const;
    virtual bool pushesUpFallingBlocks()const;
    virtual void setFriction(float);
    virtual void movedByPiston(BlockSource &, BlockPos const&)const;
    virtual void getMapColor(BlockSource &, BlockPos const&)const;
//  virtual void addProperty(BlockProperty); //TODO: incomplete function definition
    virtual void setMapColor(Color const&);
    virtual void tryToPlace(BlockSource &, BlockPos const&, Block const&, ActorBlockSyncMessage const*)const;
    virtual void setVisualShape(AABB const&);
    virtual void randomlyModifyPosition(BlockPos const&, int &)const;
    virtual bool isFenceBlock()const;
    virtual void getMappedFace(unsigned char, Block const&)const;
    virtual void setDestroyTime(float);
    virtual bool hasComparatorSignal()const;
    virtual void handleEntityInside(BlockSource &, BlockPos const&, Actor *, Vec3 &)const;
    void setCanPropagateBrightness(bool);
    void getAllowsRunes()const;
    void getBlockID()const;
//  bool hasProperty(BlockProperty)const; //TODO: incomplete function definition
    void setFlammable(int, int)const;
    void setPushesOutItems(bool);
    bool matchesStates(BlockLegacy const&)const;
    void getGravity()const;
    bool pushesOutItems()const;
    void getBlockItemId()const;
    bool isInteraction()const;
    void setIgnoreBlockForInsideCubeRenderer(bool);
    void setIsVanillaBlock(bool);
    void popResource(BlockSource &, BlockPos const&, ItemInstance const&)const;
    std::string makeInvalidStateMessage(ItemState const&)const;
    bool isStandingSign()const;
    void getExperimental()const;
    void operator!=(BlockLegacy const&)const;
    void setDefaultState(Block const&);
    bool canBeExtraBlock()const;
    void addAABB(AABB const&, AABB const*, std::vector<AABB> &)const;
    bool isEmpty()const;
    void getBlockEntityType()const;
    bool canBeBrokenFromFalling()const;
    void createWeakPtr();
    bool isAlphaTested()const;
    void getPlacementFacingAll(Actor &, BlockPos const&, float);
    void setNameId(std::string const&);
    bool isHeavy()const;
    std::string buildDescriptionName(Block const&)const;
    void getStateMask(ItemState const&)const;
//  void setCategory(CreativeItemCategory); //TODO: incomplete function definition
    void getFriction()const;
    void tryGetStateFromLegacyData(unsigned short)const;
    void setRandomTickingExtraLayer(bool)const;
    bool hasBlockEntity()const;
    bool isSolidBlockingBlock()const;
    void getDebugText(std::vector<std::string> &, BlockPos const&)const;
    void getMaterial()const;
    std::string getFullName()const;
    BlockLegacy(std::string const&, int, Material const&);
    void spawnResources(BlockSource &, BlockPos const&, float, int)const;
    std::string getRawNameId()const;
    void getCreativeCategory()const;
    bool isMobPiece()const;
    void setExperimental();
    void setCanBeExtraBlock(bool);
    void initFromDefinition(BlockDefinition const*);
    bool canPropagateBrightness()const;
    void getParticleQuantityScalar()const;
    void createBlockPermutations(unsigned int);
    void getNumPermutations()const;
    bool isVanilla()const;
    void forEachItemStateInstance(std::function<bool (ItemStateInstance const&)>)const;
    bool isDoor()const;
    void shouldRandomTickExtraLayer()const;
//  void addBlockProperty(BlockProperty); //TODO: incomplete function definition
    bool isTrapdoor()const;
    void forEachBlockPermutation(std::function<bool (Block const&)>)const;
    std::string getNamespace()const;
    std::string getDescriptionId()const;
//  void setBlockProperty(BlockProperty); //TODO: incomplete function definition
    void getDefaultState()const;
    void getDestroySpeed()const;
    void _tryGetStateFromLegacyDataUncached(unsigned short)const;
    bool hasState(ItemState const&)const;
    bool isUnbreakable()const;
    void setSolid(bool);
    void DEPRECATEDcallOnGraphicsModeChanged(bool, bool, bool);
    void setMinRequiredBaseGameVersion(BaseGameVersion const&);
    bool canInstatick()const;
    bool isSolid()const;
    void setRandomTicking(bool)const;
    void getProperties()const;
    void setIsInteraction(bool);
    void getRequiredBaseGameVersion()const;
    void ignoreBlockForInsideCubeRenderer()const;
    bool isMotionBlockingBlock()const;
    void operator==(BlockLegacy const&)const;
    void clip(BlockSource &, BlockPos const&, Vec3 const&, Vec3 const&, bool, AABB const&)const;
    void getPlacementFacingAllExceptAxisY(Actor &, BlockPos const&, float);
};
