#pragma once

#include <memory>
#include <string>
#include "../util/Tick.h"
#include <vector>


class ItemStackBase {

public:
    static long MAX_STACK_SIZE;
    static long sPickupPopDuration;
    static std::string TAG_DISPLAY;
    static std::string TAG_DISPLAY_NAME;
    static std::string TAG_LORE;
    static std::string TAG_REPAIR_COST;
    static std::string TAG_ENCHANTS;
    static std::string TAG_CAN_PLACE_ON;
    static std::string TAG_CAN_DESTROY;
    static std::string TAG_STORE_CAN_PLACE_ON;
    static std::string TAG_STORE_CAN_DESTROY;
    static std::string TAG_CHARGED_ITEM;

    ~ItemStackBase();
    void setCustomName(std::string const&);
    void setAuxValue(short);
    bool matchesItem(ItemStackBase const&)const;
    void _initComponents();
    void add(int);
    void saveEnchantsToUserData(ItemEnchants const&);
    void serializeComponents(IDataOutput &)const;
    bool isWearableItem()const;
    void getEnchantSlot()const;
    std::string getRawNameId()const;
    bool canPlaceOn(Block const*)const;
    bool hasSameUserData(std::unique_ptr<CompoundTag> const&)const;
    bool hasUserData()const;
    void getRequiredBaseGameVersion()const;
    void setShowPickUp(bool);
    bool isNull()const;
    void setBlock(Block const*);
    bool isStackable(ItemStackBase const&)const;
    void getRendererId()const;
    bool canBeCharged()const;
    std::string getHoverName()const;
    void getIdAuxEnchanted()const;
    bool isLiquidClipItem()const;
    void retrieveAuxValFromIDAux(int);
    void getEnchantsFromUserData()const;
    void getIcon(int, bool)const;
    bool isMusicDiscItem()const;
    std::string getName()const;
    ItemStackBase(RecipeIngredient const&);
    bool canDestroySpecial(Block const&)const;
    void setStackSize(unsigned char);
    void getMaxDamage()const;
    std::string getFormattedHovertext(Level &, bool)const;
    std::string getCustomLore()const;
    void setNull();
    void setPickupTime();
    void getColor()const;
    void getDescriptor()const;
    bool isDamaged()const;
    void getEnchantValue()const;
    void addCustomUserData(BlockActor &, BlockSource &);
    void _write(BinaryStream &)const;
    bool isOffhandItem()const;
    void init(int, int, int);
    void clearChargedItem();
    bool isEquivalentArmor(ItemStackBase const&)const;
    bool isValidComponent(std::string const&);
    bool isBlock()const;
    bool canDestroy(Block const*)const;
    void _loadComponents(CompoundTag const&);
    std::string toString()const;
    void startCoolDown(Player *)const;
    bool isGlint()const;
    bool hasChargedItem()const;
    void deserializeComponents(IDataInput &);
    void _makeChargedItemFromUserData();
    void refreshedInContainer(Level &);
    bool isInstance(BlockLegacy const&)const;
    bool isPotionItem()const;
    void retrieveIDFromIDAux(int);
    std::string _getHoverFormattingPrefix()const;
    void setBlockingTick(Tick);
    void remove(int);
    void _hasComponents()const;
    void load(CompoundTag const&);
    void setJustBrewed(bool);
    ItemStackBase();
    std::string getDescriptionId()const;
    void operator==(ItemStackBase const&)const;
    void addComponents(Json::Value const&, std::string &);
    void sameItemAndAux(ItemStackBase const&)const;
    void updateComponent(std::string const&, Json::Value const&);
    void getLegacyBlock()const;
    bool hasSameUserData(ItemStackBase const&)const;
    void getItem()const;
    void setChargedItem(ItemInstance const&, bool);
    void getBaseRepairCost()const;
    ItemStackBase(BlockLegacy const&, int);
    void init(Item const&, int, int, CompoundTag const*);
    bool isFullStack()const;
    bool matchesChargedItem(ItemStackBase const&)const;
    void forceSetCount(unsigned char);
    bool isValidAuxValue(int)const;
    void getStackSize()const;
    bool isEnchantingBook()const;
    bool hasCompoundTextUserData()const;
    bool isArmorItem()const;
    bool showsDurabilityInCreative()const;
    bool isValid()const;
    void _cloneComponents(ItemStackBase const&);
    bool componentsMatch(ItemStackBase const&)const;
    void getAttackDamage()const;
    void setCustomLore(std::vector<std::string> const&);
    ItemStackBase(Block const&, int, CompoundTag const*);
    void getIsValidPickupTime()const;
    bool isPattern()const;
    ItemStackBase(Item const&, int);
    ItemStackBase(Item const&);
    void getPickupTime()const;
    void getUserData()const;
    bool isStackedByData()const;
    void setRepairCost(int);
    void getAuxValue()const;
    bool isThrowable()const;
    bool isEnchanted()const;
    bool wasJustBrewed()const;
    void hurtAndBreak(int, Actor *);
    bool hasCustomHoverName()const;
    void getBlock()const;
    void _updateCompareHashes();
    void snap(Player *);
    bool isHorseArmorItem()const;
    void load(CompoundTag const&, Level &);
    void setDamageValue(short);
    void sameItem(int, int)const;
    bool isStackable()const;
    void getChargedItem()const;
    bool hasComponent(std::string const&)const;
    bool isDamageableItem()const;
//  void setPickupTime(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l>>>); //TODO: incomplete function definition
    ItemStackBase(BlockLegacy const&, int, short);
    void _setItem(int);
    void sameItem(ItemStackBase const&)const;
    ItemStackBase(Item const&, int, int, CompoundTag const*);
    bool isItem()const;
    void _saveComponents(CompoundTag &)const;
    bool isExplodable()const;
    std::string getEffectName()const;
    bool isEmptyStack()const;
    void init(BlockLegacy const&, int);
    void set(int);
    void _setChargedItem(ItemInstance const&);
    bool hasFeedingAnimation()const;
    void matches(ItemStackBase const&)const;
    void _read(ReadOnlyBinaryStream &);
    void getBlockingTick()const;
    void getNetworkUserData()const;
    void setUserData(std::unique_ptr<CompoundTag>);
    bool isInstance(Item const&)const;
    void retrieveEnchantFromIDAux(int);
    void resetHoverName();
    bool hasSameAuxValue(ItemStackBase const&)const;
    ItemStackBase(ItemStackBase const&);
    void getId()const;
    void operator!=(ItemStackBase const&)const;
    std::string getCategoryName()const;
    void getUseAnimation()const;
    bool isExperimental()const;
    void getPickupPopPercentage()const;
    void save()const;
    std::string getCustomName()const;
    void getDamageValue()const;
    void getMaxStackSize()const;
    void _loadItem(CompoundTag const&);
    void getIdAux()const;
    ItemStackBase(Item const&, int, int);
};
