#pragma once

#include <memory>
#include <functional>
#include "StubInterface.h"


namespace com {

    namespace mojang {

        namespace clacks {

            namespace protocol {

                namespace Commands {

                    class Stub : com::mojang::clacks::protocol::Commands::StubInterface {

                    public:
                        class experimental_async;

                        ~Stub(); // _ZN3com6mojang6clacks8protocol8Commands4StubD2Ev
//                      virtual void listPlayer(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::PlayerList *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub10listPlayerEPN4grpc13ClientContextERKNS2_5EmptyEPNS2_10PlayerListE
//                      virtual void kick(grpc::ClientContext *, com::mojang::clacks::protocol::PlayerAndMessage const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub4kickEPN4grpc13ClientContextERKNS2_16PlayerAndMessageEPNS2_5EmptyE
//                      virtual void say(grpc::ClientContext *, com::mojang::clacks::protocol::Message const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub3sayEPN4grpc13ClientContextERKNS2_7MessageEPNS2_5EmptyE
//                      virtual void changeSettings(grpc::ClientContext *, com::mojang::clacks::protocol::Settings const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub14changeSettingsEPN4grpc13ClientContextERKNS2_8SettingsEPNS2_5EmptyE
//                      virtual void reloadOps(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub9reloadOpsEPN4grpc13ClientContextERKNS2_5EmptyEPS8_
//                      virtual void reloadPermissions(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub17reloadPermissionsEPN4grpc13ClientContextERKNS2_5EmptyEPS8_
//                      virtual void reloadWhitelist(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub15reloadWhitelistEPN4grpc13ClientContextERKNS2_5EmptyEPS8_
//                      virtual void saveHold(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub8saveHoldEPN4grpc13ClientContextERKNS2_5EmptyEPS8_
//                      virtual void saveQuery(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::SaveQueryResult *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub9saveQueryEPN4grpc13ClientContextERKNS2_5EmptyEPNS2_15SaveQueryResultE
//                      virtual void saveResume(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub10saveResumeEPN4grpc13ClientContextERKNS2_5EmptyEPS8_
//                      virtual void saveState(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::SaveStateResult *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub9saveStateEPN4grpc13ClientContextERKNS2_5EmptyEPNS2_15SaveStateResultE
//                      virtual void stop(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub4stopEPN4grpc13ClientContextERKNS2_5EmptyEPS8_
//                      virtual void serverStarted(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub13serverStartedEPN4grpc13ClientContextERKNS2_5EmptyEPS8_
                        virtual void experimental_async(); // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_asyncEv
//                      virtual void AsynclistPlayerRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18AsynclistPlayerRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void PrepareAsynclistPlayerRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub25PrepareAsynclistPlayerRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void AsynckickRaw(grpc::ClientContext *, com::mojang::clacks::protocol::PlayerAndMessage const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub12AsynckickRawEPN4grpc13ClientContextERKNS2_16PlayerAndMessageEPNS5_15CompletionQueueE
//                      virtual void PrepareAsynckickRaw(grpc::ClientContext *, com::mojang::clacks::protocol::PlayerAndMessage const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub19PrepareAsynckickRawEPN4grpc13ClientContextERKNS2_16PlayerAndMessageEPNS5_15CompletionQueueE
//                      virtual void AsyncsayRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Message const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub11AsyncsayRawEPN4grpc13ClientContextERKNS2_7MessageEPNS5_15CompletionQueueE
//                      virtual void PrepareAsyncsayRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Message const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18PrepareAsyncsayRawEPN4grpc13ClientContextERKNS2_7MessageEPNS5_15CompletionQueueE
//                      virtual void AsyncchangeSettingsRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Settings const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub22AsyncchangeSettingsRawEPN4grpc13ClientContextERKNS2_8SettingsEPNS5_15CompletionQueueE
//                      virtual void PrepareAsyncchangeSettingsRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Settings const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub29PrepareAsyncchangeSettingsRawEPN4grpc13ClientContextERKNS2_8SettingsEPNS5_15CompletionQueueE
//                      virtual void AsyncreloadOpsRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub17AsyncreloadOpsRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void PrepareAsyncreloadOpsRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub24PrepareAsyncreloadOpsRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void AsyncreloadPermissionsRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub25AsyncreloadPermissionsRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void PrepareAsyncreloadPermissionsRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub32PrepareAsyncreloadPermissionsRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void AsyncreloadWhitelistRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub23AsyncreloadWhitelistRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void PrepareAsyncreloadWhitelistRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub30PrepareAsyncreloadWhitelistRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void AsyncsaveHoldRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub16AsyncsaveHoldRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void PrepareAsyncsaveHoldRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub23PrepareAsyncsaveHoldRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void AsyncsaveQueryRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub17AsyncsaveQueryRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void PrepareAsyncsaveQueryRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub24PrepareAsyncsaveQueryRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void AsyncsaveResumeRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18AsyncsaveResumeRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void PrepareAsyncsaveResumeRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub25PrepareAsyncsaveResumeRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void AsyncsaveStateRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub17AsyncsaveStateRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void PrepareAsyncsaveStateRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub24PrepareAsyncsaveStateRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void AsyncstopRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub12AsyncstopRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void PrepareAsyncstopRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub19PrepareAsyncstopRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void AsyncserverStartedRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub21AsyncserverStartedRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void PrepareAsyncserverStartedRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub28PrepareAsyncserverStartedRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
//                      virtual void subscribeToMetricsRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub21subscribeToMetricsRawEPN4grpc13ClientContextERKNS2_5EmptyE
//                      virtual void AsyncsubscribeToMetricsRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *, void *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub26AsyncsubscribeToMetricsRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueEPv
//                      virtual void PrepareAsyncsubscribeToMetricsRaw(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const&, grpc::CompletionQueue *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub33PrepareAsyncsubscribeToMetricsRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        Stub(std::shared_ptr<grpc::ChannelInterface> const&); // _ZN3com6mojang6clacks8protocol8Commands4StubC2ERKSt10shared_ptrIN4grpc16ChannelInterfaceEE
                        class experimental_async : com::mojang::clacks::protocol::Commands::StubInterface::experimental_async_interface {

                        public:
                            ~experimental_async(); // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_asyncD2Ev
//                          virtual void listPlayer(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::PlayerList *, std::function<void (grpc::Status)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async10listPlayerEPN4grpc13ClientContextEPKNS2_5EmptyEPNS2_10PlayerListESt8functionIFvNS6_6StatusEEE
//                          virtual void kick(grpc::ClientContext *, com::mojang::clacks::protocol::PlayerAndMessage const*, com::mojang::clacks::protocol::Empty *, std::function<void (grpc::Status)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async4kickEPN4grpc13ClientContextEPKNS2_16PlayerAndMessageEPNS2_5EmptyESt8functionIFvNS6_6StatusEEE
//                          virtual void say(grpc::ClientContext *, com::mojang::clacks::protocol::Message const*, com::mojang::clacks::protocol::Empty *, std::function<void (grpc::Status)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async3sayEPN4grpc13ClientContextEPKNS2_7MessageEPNS2_5EmptyESt8functionIFvNS6_6StatusEEE
//                          virtual void changeSettings(grpc::ClientContext *, com::mojang::clacks::protocol::Settings const*, com::mojang::clacks::protocol::Empty *, std::function<void (grpc::Status)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async14changeSettingsEPN4grpc13ClientContextEPKNS2_8SettingsEPNS2_5EmptyESt8functionIFvNS6_6StatusEEE
//                          virtual void reloadOps(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty *, std::function<void (grpc::Status)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async9reloadOpsEPN4grpc13ClientContextEPKNS2_5EmptyEPS9_St8functionIFvNS6_6StatusEEE
//                          virtual void reloadPermissions(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty *, std::function<void (grpc::Status)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async17reloadPermissionsEPN4grpc13ClientContextEPKNS2_5EmptyEPS9_St8functionIFvNS6_6StatusEEE
//                          virtual void reloadWhitelist(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty *, std::function<void (grpc::Status)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async15reloadWhitelistEPN4grpc13ClientContextEPKNS2_5EmptyEPS9_St8functionIFvNS6_6StatusEEE
//                          virtual void saveHold(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty *, std::function<void (grpc::Status)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async8saveHoldEPN4grpc13ClientContextEPKNS2_5EmptyEPS9_St8functionIFvNS6_6StatusEEE
//                          virtual void saveQuery(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::SaveQueryResult *, std::function<void (grpc::Status)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async9saveQueryEPN4grpc13ClientContextEPKNS2_5EmptyEPNS2_15SaveQueryResultESt8functionIFvNS6_6StatusEEE
//                          virtual void saveResume(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty *, std::function<void (grpc::Status)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async10saveResumeEPN4grpc13ClientContextEPKNS2_5EmptyEPS9_St8functionIFvNS6_6StatusEEE
//                          virtual void saveState(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::SaveStateResult *, std::function<void (grpc::Status)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async9saveStateEPN4grpc13ClientContextEPKNS2_5EmptyEPNS2_15SaveStateResultESt8functionIFvNS6_6StatusEEE
//                          virtual void stop(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty *, std::function<void (grpc::Status)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async4stopEPN4grpc13ClientContextEPKNS2_5EmptyEPS9_St8functionIFvNS6_6StatusEEE
//                          virtual void serverStarted(grpc::ClientContext *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty *, std::function<void (grpc::Status)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async13serverStartedEPN4grpc13ClientContextEPKNS2_5EmptyEPS9_St8functionIFvNS6_6StatusEEE
//                          virtual void subscribeToMetrics(grpc::ClientContext *, com::mojang::clacks::protocol::Empty *, grpc::experimental::ClientReadReactor<com::mojang::clacks::protocol::MetricReport> *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async18subscribeToMetricsEPN4grpc13ClientContextEPNS2_5EmptyEPNS6_12experimental17ClientReadReactorINS2_12MetricReportEEE
                            experimental_async(com::mojang::clacks::protocol::Commands::Stub *); // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_asyncC2EPS4_
                        };
                    };
                }
            }
        }
    }
}
