#pragma once

#include <memory>
#include <functional>
#include "StubInterface.h"


namespace com {

    namespace mojang {

        namespace clacks {

            namespace protocol {

                namespace Commands {

                    class Stub : public com::mojang::clacks::protocol::Commands::StubInterface {

                    public:
                        class experimental_async;

                        virtual ~Stub(); // _ZN3com6mojang6clacks8protocol8Commands4StubD2Ev
                        virtual void __fake_function0(); // fake
                        virtual void listPlayer__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::PlayerList *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub10listPlayerEPN4grpc13ClientContextERKNS2_5EmptyEPNS2_10PlayerListE
                        virtual void kick__incomplete0(long *, com::mojang::clacks::protocol::PlayerAndMessage const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub4kickEPN4grpc13ClientContextERKNS2_16PlayerAndMessageEPNS2_5EmptyE
                        virtual void say__incomplete0(long *, com::mojang::clacks::protocol::Message const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub3sayEPN4grpc13ClientContextERKNS2_7MessageEPNS2_5EmptyE
                        virtual void changeSettings__incomplete0(long *, com::mojang::clacks::protocol::Settings const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub14changeSettingsEPN4grpc13ClientContextERKNS2_8SettingsEPNS2_5EmptyE
                        virtual void reloadOps__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub9reloadOpsEPN4grpc13ClientContextERKNS2_5EmptyEPS8_
                        virtual void reloadPermissions__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub17reloadPermissionsEPN4grpc13ClientContextERKNS2_5EmptyEPS8_
                        virtual void reloadWhitelist__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub15reloadWhitelistEPN4grpc13ClientContextERKNS2_5EmptyEPS8_
                        virtual void saveHold__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub8saveHoldEPN4grpc13ClientContextERKNS2_5EmptyEPS8_
                        virtual void saveQuery__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::SaveQueryResult *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub9saveQueryEPN4grpc13ClientContextERKNS2_5EmptyEPNS2_15SaveQueryResultE
                        virtual void saveResume__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub10saveResumeEPN4grpc13ClientContextERKNS2_5EmptyEPS8_
                        virtual void saveState__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::SaveStateResult *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub9saveStateEPN4grpc13ClientContextERKNS2_5EmptyEPNS2_15SaveStateResultE
                        virtual void stop__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub4stopEPN4grpc13ClientContextERKNS2_5EmptyEPS8_
                        virtual void serverStarted__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, com::mojang::clacks::protocol::Empty *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub13serverStartedEPN4grpc13ClientContextERKNS2_5EmptyEPS8_
                        virtual void experimental_async(); // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_asyncEv
                        virtual void AsynclistPlayerRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18AsynclistPlayerRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void PrepareAsynclistPlayerRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub25PrepareAsynclistPlayerRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void AsynckickRaw__incomplete0(long *, com::mojang::clacks::protocol::PlayerAndMessage const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub12AsynckickRawEPN4grpc13ClientContextERKNS2_16PlayerAndMessageEPNS5_15CompletionQueueE
                        virtual void PrepareAsynckickRaw__incomplete0(long *, com::mojang::clacks::protocol::PlayerAndMessage const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub19PrepareAsynckickRawEPN4grpc13ClientContextERKNS2_16PlayerAndMessageEPNS5_15CompletionQueueE
                        virtual void AsyncsayRaw__incomplete0(long *, com::mojang::clacks::protocol::Message const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub11AsyncsayRawEPN4grpc13ClientContextERKNS2_7MessageEPNS5_15CompletionQueueE
                        virtual void PrepareAsyncsayRaw__incomplete0(long *, com::mojang::clacks::protocol::Message const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18PrepareAsyncsayRawEPN4grpc13ClientContextERKNS2_7MessageEPNS5_15CompletionQueueE
                        virtual void AsyncchangeSettingsRaw__incomplete0(long *, com::mojang::clacks::protocol::Settings const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub22AsyncchangeSettingsRawEPN4grpc13ClientContextERKNS2_8SettingsEPNS5_15CompletionQueueE
                        virtual void PrepareAsyncchangeSettingsRaw__incomplete0(long *, com::mojang::clacks::protocol::Settings const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub29PrepareAsyncchangeSettingsRawEPN4grpc13ClientContextERKNS2_8SettingsEPNS5_15CompletionQueueE
                        virtual void AsyncreloadOpsRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub17AsyncreloadOpsRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void PrepareAsyncreloadOpsRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub24PrepareAsyncreloadOpsRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void AsyncreloadPermissionsRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub25AsyncreloadPermissionsRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void PrepareAsyncreloadPermissionsRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub32PrepareAsyncreloadPermissionsRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void AsyncreloadWhitelistRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub23AsyncreloadWhitelistRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void PrepareAsyncreloadWhitelistRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub30PrepareAsyncreloadWhitelistRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void AsyncsaveHoldRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub16AsyncsaveHoldRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void PrepareAsyncsaveHoldRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub23PrepareAsyncsaveHoldRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void AsyncsaveQueryRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub17AsyncsaveQueryRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void PrepareAsyncsaveQueryRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub24PrepareAsyncsaveQueryRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void AsyncsaveResumeRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18AsyncsaveResumeRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void PrepareAsyncsaveResumeRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub25PrepareAsyncsaveResumeRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void AsyncsaveStateRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub17AsyncsaveStateRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void PrepareAsyncsaveStateRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub24PrepareAsyncsaveStateRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void AsyncstopRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub12AsyncstopRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void PrepareAsyncstopRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub19PrepareAsyncstopRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void AsyncserverStartedRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub21AsyncserverStartedRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void PrepareAsyncserverStartedRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub28PrepareAsyncserverStartedRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        virtual void subscribeToMetricsRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub21subscribeToMetricsRawEPN4grpc13ClientContextERKNS2_5EmptyE
                        virtual void AsyncsubscribeToMetricsRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *, void *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub26AsyncsubscribeToMetricsRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueEPv
                        virtual void PrepareAsyncsubscribeToMetricsRaw__incomplete0(long *, com::mojang::clacks::protocol::Empty const&, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub33PrepareAsyncsubscribeToMetricsRawEPN4grpc13ClientContextERKNS2_5EmptyEPNS5_15CompletionQueueE
                        Stub(std::shared_ptr<long> const&); // _ZN3com6mojang6clacks8protocol8Commands4StubC2ERKSt10shared_ptrIN4grpc16ChannelInterfaceEE
                        class experimental_async : public com::mojang::clacks::protocol::Commands::StubInterface::experimental_async_interface {

                        public:
                            virtual ~experimental_async(); // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_asyncD2Ev
                            virtual void __fake_function0(); // fake
                            virtual void listPlayer__incomplete0(long *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::PlayerList *, std::function<void (long)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async10listPlayerEPN4grpc13ClientContextEPKNS2_5EmptyEPNS2_10PlayerListESt8functionIFvNS6_6StatusEEE
                            virtual void kick__incomplete0(long *, com::mojang::clacks::protocol::PlayerAndMessage const*, com::mojang::clacks::protocol::Empty *, std::function<void (long)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async4kickEPN4grpc13ClientContextEPKNS2_16PlayerAndMessageEPNS2_5EmptyESt8functionIFvNS6_6StatusEEE
                            virtual void say__incomplete0(long *, com::mojang::clacks::protocol::Message const*, com::mojang::clacks::protocol::Empty *, std::function<void (long)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async3sayEPN4grpc13ClientContextEPKNS2_7MessageEPNS2_5EmptyESt8functionIFvNS6_6StatusEEE
                            virtual void changeSettings__incomplete0(long *, com::mojang::clacks::protocol::Settings const*, com::mojang::clacks::protocol::Empty *, std::function<void (long)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async14changeSettingsEPN4grpc13ClientContextEPKNS2_8SettingsEPNS2_5EmptyESt8functionIFvNS6_6StatusEEE
                            virtual void reloadOps__incomplete0(long *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty *, std::function<void (long)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async9reloadOpsEPN4grpc13ClientContextEPKNS2_5EmptyEPS9_St8functionIFvNS6_6StatusEEE
                            virtual void reloadPermissions__incomplete0(long *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty *, std::function<void (long)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async17reloadPermissionsEPN4grpc13ClientContextEPKNS2_5EmptyEPS9_St8functionIFvNS6_6StatusEEE
                            virtual void reloadWhitelist__incomplete0(long *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty *, std::function<void (long)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async15reloadWhitelistEPN4grpc13ClientContextEPKNS2_5EmptyEPS9_St8functionIFvNS6_6StatusEEE
                            virtual void saveHold__incomplete0(long *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty *, std::function<void (long)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async8saveHoldEPN4grpc13ClientContextEPKNS2_5EmptyEPS9_St8functionIFvNS6_6StatusEEE
                            virtual void saveQuery__incomplete0(long *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::SaveQueryResult *, std::function<void (long)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async9saveQueryEPN4grpc13ClientContextEPKNS2_5EmptyEPNS2_15SaveQueryResultESt8functionIFvNS6_6StatusEEE
                            virtual void saveResume__incomplete0(long *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty *, std::function<void (long)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async10saveResumeEPN4grpc13ClientContextEPKNS2_5EmptyEPS9_St8functionIFvNS6_6StatusEEE
                            virtual void saveState__incomplete0(long *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::SaveStateResult *, std::function<void (long)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async9saveStateEPN4grpc13ClientContextEPKNS2_5EmptyEPNS2_15SaveStateResultESt8functionIFvNS6_6StatusEEE
                            virtual void stop__incomplete0(long *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty *, std::function<void (long)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async4stopEPN4grpc13ClientContextEPKNS2_5EmptyEPS9_St8functionIFvNS6_6StatusEEE
                            virtual void serverStarted__incomplete0(long *, com::mojang::clacks::protocol::Empty const*, com::mojang::clacks::protocol::Empty *, std::function<void (long)>); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async13serverStartedEPN4grpc13ClientContextEPKNS2_5EmptyEPS9_St8functionIFvNS6_6StatusEEE
                            virtual void subscribeToMetrics__incomplete0(long *, com::mojang::clacks::protocol::Empty *, long *); //TODO: incomplete function definition // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_async18subscribeToMetricsEPN4grpc13ClientContextEPNS2_5EmptyEPNS6_12experimental17ClientReadReactorINS2_12MetricReportEEE
                            experimental_async(com::mojang::clacks::protocol::Commands::Stub *); // _ZN3com6mojang6clacks8protocol8Commands4Stub18experimental_asyncC2EPS4_
                        };
                    };
                }
            }
        }
    }
}
